# Generated by Django 5.0.2 on 2024-06-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ref_no', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('consumer_name', models.CharField(max_length=255)),
                ('consumer_address', models.CharField(max_length=255)),
                ('ssn', models.CharField(max_length=20)),
            ],
        ),
    ]
